# Use an official Python runtime as a parent image

FROM python:3.8

# Set the working directory to /app

WORKDIR /app

# Copy the current directory contents into the container at /app

COPY ./dashboard /app

# Install any needed packages specified in requirements.txt

RUN pip install -r requirements.txt

# Make port 8050 available to the world outside this container

EXPOSE 8050

# Run the Dash app

CMD ["python", "app.py"]
